language: ruby
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
rvm:
  - 2.5

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install
  - npm install -g firebase-tools

script: JEKYLL_ENV=production bundle exec jekyll build

after_success:
  firebase deploy --token "${FIREBASE_TOKEN}"

branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
