url: https://www.karimabennoune.com
# baseurl: karimabennoune.com
sitename: 'Karima Bennoune'
description: 'Karima Bennoune, author of Your Fatwa Does Not Apply Here: Untold stories from the fight against Muslim fundamentalism.'

# do not include  https://github.com/...
repo: 'budparr/jekyll-starter'
branch: master
default_author: "Karima Bennoune"
port: 3900


categories:  
  - journal
  - articles
  - reviews
  - appearances
  
#Jekyll Options
# if using more than one Jekyll instance on your local machine
# port:
# paginate tells Jekyll how many posts per page
# paginate: 1
# Permalinks
permalink:  pretty
# Dependencies
# extensions: ['autolink', 'smart']

#Pages - store all pages in the _pages directory
include: ['_pages']
relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','bower_components','license.md','Gemfile', 'Gemfile.lock','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'README.md', 'prose.yaml']
gems:
  - jekyll-archives
  - jekyll-seo-tag
jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    category: '/:name/'

plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes
 
# dev options (true/false)
# if site is in production, 'production: true'
production: true
use_pure_css: false
use_jquery_cdn: true
include_font_awesome: false
include_addthis_sharing: false
bust_css_cache: true

# options (data)
google_analytics_id: UA-42475377-4
disqus_id:
addthis_id:
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:
directory_assets_img: /assets/img/

# options (social)
# facebook_id:
twitter_id: budparr

# navigation options - effects layout/default. May also need options set in sass files
include_nav-top: true
include_nav-side-left: true
include_nav-side-right: false

sass:
    style: :compressed
    sass_dir: assets/css/_sass

collections:
  books:
    output: true
  landing_pages:
    output: true
    permalink: '/:path/'
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: article
  - scope:
      path: ''
      type: 'landing_pages'
    values:
      layout: page